//! Core contracts and state machines for Grok Build Desktop.
//!
//! This crate defines the contracts shared by every layer, enforces the
//! invariants that must hold before work reaches the runner, and owns the
//! `SQLite` event ledger used to reconstruct durable sprint state. It contains
//! no UI, provider, or platform-sandbox implementation.

mod application_composition;
mod completion;
mod contracts;
mod current_final_verification_evidence;
mod final_verification_contracts;
mod ledger;
mod live_state;
mod optimal_finish;
mod scheduler;
mod state;
mod trust;

pub use application_composition::{
    APPLICATION_ARTIFACT_COMPOSER_VERSION_V2, AggregateCompositionResultMaterialV2,
    ApplicationArtifactCompositionReceiptV2, COMPOSITION_SOURCE_BUNDLE_FORMAT_VERSION_V2,
    CompositionAggregateBlobReadbackV2, CompositionAggregateCreateModeReadbackV2,
    CompositionBaseDirectoryV2, CompositionBaseFileV2, CompositionConflict,
    CompositionEndpointKindV2, CompositionFinalVerificationBindingV2,
    CompositionResultMaterialKindV2, CompositionResultMaterialV2, CompositionSourceDigestKind,
    CompositionSourceShapeConflict, MAX_COMPOSITION_CANONICAL_INPUT_BYTES_V2,
    MAX_COMPOSITION_FILE_BYTES_V2, MAX_COMPOSITION_IDENTIFIER_BYTES_V2,
    MAX_COMPOSITION_OPERATIONS_V2, MAX_COMPOSITION_REOPENED_SOURCE_BYTES_V2,
    MAX_COMPOSITION_REOPENED_SOURCE_METADATA_BYTES_V2,
    MAX_COMPOSITION_REOPENED_SOURCE_OPERATIONS_V2, MAX_COMPOSITION_SOURCES_V2,
    MAX_COMPOSITION_TOTAL_BYTES_V2, NonAuthorizingApplicationCompositionAggregateReadbackV2,
    NonAuthorizingApplicationCompositionInputsV2, NonAuthorizingApplicationCompositionPlanV2,
    NonAuthorizingApplicationCompositionPublicationClaimV2,
    NonAuthorizingApplicationCompositionPublicationClosureV2,
    NonAuthorizingApplicationCompositionSourceAuthorityV2,
    NonAuthorizingApplicationCompositionSourceReadbackV2,
    NonAuthorizingApplicationCompositionSourceV2, NonAuthorizingCompositionBaseProjectionV2,
    NonAuthorizingCompositionDerivationRecordV2, PortablePathConflictKind,
    derive_non_authorizing_application_composition_v2,
};

pub use completion::{
    CompletionApplicationAssessment, CompletionAssessment, CompletionEvidence,
    CompletionRequirement, assess_completion,
};
pub use contracts::{
    AcceptanceCriterion, AcceptanceEvidence, AcceptanceKind, AcceptanceReceipt, AgentEvent,
    AgentEventKind, ApplicationEvidence, ApplicationReceipt, ApplicationRequest,
    ApplicationValidationEvidence, ApplicationValidationMode,
    COMMAND_OUTPUT_ARTIFACT_FORMAT_VERSION, ChangeSet, CommandOutputArtifactSetReferenceV1,
    CommandOutputArtifactSourceV1, CommandOutputStreamArtifactV1, CommandOutputStreamV1,
    CommandSpec, CommandTerminationV1, CompletionApplication, CompletionReceipt, ContractError,
    CriterionEvidenceReceiptV2, Digest, EffectIntent, EffectKind, EffectObservation, EffectOutcome,
    EffectReconciliation, EnvironmentVariable, ExecutionNetwork, ExecutionOrigin, ExecutionPolicy,
    FileOperation, FinalReport, HumanAcceptanceBackingV1, HumanAcceptanceDecisionOutcomeV1,
    HumanAcceptanceDecisionV1, HumanAcceptancePromptV1, LegacyTaskAttemptClassification,
    LiveConflictReceipt, LiveConflictUserDecision, LivePathConflict, LiveWorkspaceUnchangedReceipt,
    MAX_APPLICATION_REQUEST_BYTES, MAX_COMMAND_OUTPUT_ARTIFACT_ID_BYTES,
    MAX_TASK_ATTEMPT_EVIDENCE_BYTES, MAX_TASK_ATTEMPT_ID_BYTES, MAX_TASK_INTEGRATION_REQUEST_BYTES,
    MAX_TERMINAL_REASON_BYTES, MAX_WORKER_ID_BYTES, MutationArtifactLink, MutationMode,
    NonSuccessTerminalState, PathScope, ProviderProfile, ProviderResponse, ProviderResponseResult,
    ResourceLimits, RollbackEvidence, RollbackReceipt, RollbackReference,
    RollbackReferenceEvidence, RollbackRequest, RollbackValidationEvidence, RollbackValidationMode,
    RunnerLaunchIntent, RunnerSessionPolicyRecord, RunnerSessionPurpose, SprintBudget, SprintSpec,
    SprintTerminalEvidence, SprintUnknownTerminalizationClosure,
    SprintUnknownTerminalizationPending, TaskAttempt, TaskAttemptAttemptsExhaustedDisposition,
    TaskAttemptBlockedCause, TaskAttemptBlockedDisposition, TaskAttemptBudgetClassification,
    TaskAttemptCanceledCause, TaskAttemptCanceledDisposition, TaskAttemptCandidateBoundary,
    TaskAttemptCleanupRelease, TaskAttemptDisposition, TaskAttemptDispositionMetadata,
    TaskAttemptEvidence, TaskAttemptEvidenceKind, TaskAttemptFormalCheck, TaskAttemptHistory,
    TaskAttemptHistoryEntry, TaskAttemptIntegratedDisposition, TaskAttemptKnownCleanupOutcome,
    TaskAttemptLeaseState, TaskAttemptPermanentFailureCause,
    TaskAttemptPermanentFailureDisposition, TaskAttemptRecoveryDecision, TaskAttemptRecoveryFacts,
    TaskAttemptReleaseProof, TaskAttemptRetryableCause, TaskAttemptRetryableDisposition,
    TaskAttemptRunningBoundary, TaskAttemptTerminalEffect, TaskAttemptUncertainEvidence,
    TaskAttemptUnknownCleanedDisposition, TaskAttemptUnknownEvidence,
    TaskAttemptUnknownQuarantinedDisposition, TaskAttemptVerificationBoundary, TaskGraph,
    TaskIntegrationArtifactReference, TaskIntegrationEvidence, TaskIntegrationReceipt,
    TaskIntegrationRequest, TaskIntegrationValidationEvidence, TaskIntegrationValidationMode,
    TaskSpec, VerificationEffectEvidence, VerificationReceipt, VerifiedNoOpReceipt,
    WORKER_LEASE_ID_BYTES, WorkerCleanupBackend, WorkerCleanupEvidence, WorkerCleanupReceipt,
    WorkerCleanupRequest, WorkerLease, WorkerLeaseNeverLaunchedRelease, WorkspaceGrant,
    WorkspaceNetworkPolicy, WorkspacePermissions, WorkspaceSnapshot,
    validate_current_direct_exec_command_v1,
};
pub use current_final_verification_evidence::{
    AuthenticatedCurrentFinalVerificationControlActionV2,
    CURRENT_FINAL_VERIFICATION_EVIDENCE_VERSION_V2, CurrentCommandDomainBackendV2,
    CurrentCommandDomainCleanupObservationV2, CurrentCommandDomainCleanupSourceV2,
    CurrentFinalVerificationCaptureAcquiredFrontierV2, CurrentFinalVerificationControlActionKindV2,
    CurrentFinalVerificationControlResolutionSourceV2,
    CurrentFinalVerificationDispatchedFrontierV2, CurrentFinalVerificationEffectCutObservationV2,
    CurrentFinalVerificationEffectCutSourceV2, CurrentFinalVerificationIdentitySpineFieldsV2,
    CurrentFinalVerificationIdentitySpineV2, CurrentFinalVerificationLaunchCommittedFrontierV2,
    CurrentFinalVerificationLifecycleReservationFieldsV2,
    CurrentFinalVerificationLifecycleReservationSetV2, CurrentFinalVerificationMissingSourceV2,
    CurrentFinalVerificationNativeContainmentBackendV2,
    CurrentFinalVerificationOutputCustodyObservationV2,
    CurrentFinalVerificationOutputCustodySourceV2,
    CurrentFinalVerificationPreEffectAbandonmentReasonV2,
    CurrentFinalVerificationReachedFrontierV2, CurrentFinalVerificationTerminalObservationV2,
    CurrentFinalVerificationTerminalSourceV2, CurrentFinalVerificationUnknownReasonV2,
    CurrentFinalVerificationV13InitializedFrontierV2, CurrentIndependentDirectChildObservationV2,
    CurrentIndependentRunnerDomainObservationV2, CurrentRunnerCleanupSourceV2,
    CurrentRunnerShutdownTranscriptV2, MAX_CURRENT_FINAL_VERIFICATION_CANONICAL_BYTES_V2,
    MAX_CURRENT_FINAL_VERIFICATION_CONTROL_ACTIONS_V2,
    MAX_CURRENT_FINAL_VERIFICATION_IDENTIFIER_BYTES_V2,
    NonAuthorizingCurrentFinalVerificationDerivationV2,
    NonAuthorizingCurrentFinalVerificationDerivedOutcomeKindV2,
    NonAuthorizingCurrentFinalVerificationDerivedOutcomeV2,
    NonAuthorizingCurrentFinalVerificationEvidenceClosureV2,
    NonAuthorizingCurrentFinalVerificationEvidenceErrorV2,
    NonAuthorizingCurrentFinalVerificationEvidenceInputsV2,
    derive_non_authorizing_current_final_verification_evidence_v2,
};
pub use final_verification_contracts::{
    FINAL_VERIFICATION_ATTEMPT_AUTHORITY_VERSION_V1, FinalVerificationAttemptAuthorityV1,
    FinalVerificationAttemptExpectedInputsV1, FinalVerificationAttemptPredecessorV1,
    FinalVerificationAttemptProvenanceV1, LegacySprintBudgetV1, LegacySprintSpecV1,
    LegacyTaskGraphV1, LegacyTaskSpecV1, MAX_FINAL_VERIFICATION_ATTEMPTS,
    MIN_FINAL_VERIFICATION_ATTEMPTS, PRODUCT_DEFAULT_MAX_FINAL_VERIFICATION_ATTEMPTS_V01,
    SPRINT_AUTHORITY_CONTRACT_VERSION_V2, SprintBudgetV2, SprintSpecV2, TaskGraphV2, TaskPurposeV2,
    TaskSpecV2,
};
pub use ledger::{
    ApplicationArtifactAssembly, ApplicationArtifactAssemblySource,
    ApplicationRequestArtifactAuthority, COMMAND_OUTPUT_CAPTURE_DRAIN_ALLOWANCE_BYTES_V1,
    COMMAND_OUTPUT_CAPTURE_LAYOUT_VERSION, ClaimedObservationWriteFailure, CommandDomainBackend,
    CommandDomainCleanupCompleteness, CommandDomainCleanupDisposition,
    CommandDomainCleanupIncomplete, CommandDomainCleanupProof, CommandDomainEffectBinding,
    CommandDomainEffectState, CommandOutputAbandonmentReasonV2, CommandOutputCaptureAcquiredV1,
    CommandOutputCaptureDirectoryIdentityV1, CommandOutputCaptureFileIdentityV1,
    CommandOutputCaptureIntentAdmission, CommandOutputCaptureIntentV1,
    CommandOutputCaptureLaunchHistoryV1, CommandOutputCaptureObservationClassV1,
    CommandOutputCapturePendingResolutionV1, CommandOutputCapturePhysicalHistoryEntryV1,
    CommandOutputCapturePhysicalReconciliationV1, CommandOutputCapturePhysicalResolutionActionV1,
    CommandOutputCapturePhysicalTerminalEvidenceV1, CommandOutputCaptureReconciliationAdmission,
    CommandOutputCaptureReconciliationClaimV1, CommandOutputCaptureReconciliationPermit,
    CommandOutputCaptureReconciliationResolutionV1, CommandOutputCaptureRecovery,
    CommandOutputCaptureRestartLaunchEvidenceV1, CommandOutputCaptureRestartRecoveryReceiptV1,
    CommandOutputCaptureRestartStateV1, CommandOutputCaptureStoreHeadV1,
    CommandOutputCaptureTerminalAnchorV1, CommandOutputCaptureTerminalDispositionV1,
    CommandOutputCaptureUnknownResolutionWriteFailure, CommandOutputCleanScanPublicationReceiptV1,
    CommandOutputCleanScanResolutionReceiptV1, CommandOutputPublicationAuthorityV1,
    CommandOutputSensitiveRejectionAnchorV1, CommandOutputSensitiveRejectionCleanupReceiptV1,
    CommandOutputSensitiveRejectionClosureV1, CompleteCommandDomainCleanupSet,
    CompleteCriterionEvidenceSetV1, CompleteTaskDoneSetV1, CompletionEligibilityAssessment,
    CompletionEligibilityRequirement, ContainedCommandReleaseAdmissionRecord,
    ContainedCommandReleaseDisposition, CurrentCriterionEvidenceKindV1,
    CurrentCriterionEvidenceMemberV1, CurrentFinalVerificationAdmissionRequestV1,
    CurrentFinalVerificationAuthorityEventKindV1, CurrentFinalVerificationAuthorityEventV1,
    CurrentFinalVerificationCaptureAcquisitionAuthorityV1,
    CurrentFinalVerificationCaptureAcquisitionCommitV1,
    CurrentFinalVerificationCaptureAcquisitionRequestV1, CurrentFinalVerificationCaptureClosureV1,
    CurrentFinalVerificationControlKindV1, CurrentFinalVerificationControlV1,
    CurrentFinalVerificationLaunchAuthorityV1, CurrentFinalVerificationLaunchCommitV1,
    CurrentFinalVerificationLaunchPreparationV1, CurrentFinalVerificationLaunchRequestV1,
    CurrentFinalVerificationNativeCleanupObligationV1,
    CurrentFinalVerificationNativePreparationAttemptV1,
    CurrentFinalVerificationNativePreparationCommitV1,
    CurrentFinalVerificationNativePreparationErrorV1,
    CurrentFinalVerificationNativePreparationOutcomeV1,
    CurrentFinalVerificationNativePreparationReadinessV1,
    CurrentFinalVerificationNativePreparationSourcePayloadV1,
    CurrentFinalVerificationNativeSourceConsumptionV1, CurrentFinalVerificationOutcomeKindV1,
    CurrentFinalVerificationOutputCustodyV1, CurrentFinalVerificationRepairActivationV1,
    CurrentFinalVerificationRepairCompletionRequestV1, CurrentFinalVerificationRepairCompletionV1,
    CurrentFinalVerificationTerminationV1, CurrentRepairActivationPermitV1,
    CurrentSprintAuthorityV32, CurrentSprintTerminalOutcomeV1, CurrentSprintTerminalReasonV1,
    CurrentTaskDoneAttemptClosureV1, CurrentTaskDoneAttemptDispositionV1,
    CurrentTaskDoneAutomatedCheckV1, CurrentTaskDoneIntegrationEvidenceV1,
    CurrentTaskDoneIntegrationSourceV1, CurrentTaskDoneMemberV1, CurrentTaskDoneSourceReceiptV1,
    EventLedger, FreshApplicationDispatchPermit,
    FreshCurrentFinalVerificationCaptureAcquisitionPermitV1,
    FreshCurrentFinalVerificationNativeLaunchPermitV1,
    FreshCurrentFinalVerificationNativePreparationRetryCustodyV1,
    FreshCurrentFinalVerificationV38PermitV1, FreshFinalVerificationDispatchPermit,
    FreshLiveStateCaptureDispatchPermit, FreshNativePreparationPlatformAdmissionV1,
    FreshRollbackDispatchPermit, FreshRunnerEffectDispatchPermit,
    FreshTaskFormalCheckDispatchPermit, FreshTaskIntegrationDispatchPermit,
    FreshTaskRunningEffectDispatchPermit, HumanAcceptanceConsumptionV1, LedgerError,
    LedgerTaskAttemptRecoveryProjection, LegacyCompletionUnproven,
    LiveContainedCommandReleaseClaim, LiveCurrentFinalVerificationNativePreparationClaimV1,
    LiveRunnerCleanupClaim, LiveRunnerLaunchPreparationClaim, LiveRunnerLaunchReleaseClaim,
    MAX_COMMAND_DOMAIN_EFFECTS_PER_SESSION, MAX_COMMAND_DOMAIN_PLATFORM_PROOF_BYTES,
    MAX_COMMAND_OUTPUT_CAPTURE_AGGREGATE_BYTES, MAX_COMMAND_OUTPUT_CAPTURE_RECONCILIATION_TTL_MS,
    MAX_COMMAND_OUTPUT_CAPTURE_RESTART_LAUNCH_BINDING_BYTES, MAX_EFFECT_EVIDENCE_BYTES,
    MAX_EFFECT_REQUEST_BYTES, MAX_POST_COMPLETION_APPLICATION_ARTIFACT_AUTHORITY_BYTES,
    MAX_POST_COMPLETION_ROLLBACK_LAUNCH_FAILURE_EVIDENCE_BYTES,
    MAX_POST_COMPLETION_ROLLBACK_REASON_BYTES, MAX_POST_COMPLETION_ROLLBACK_UNKNOWN_EVIDENCE_BYTES,
    MAX_RUNNER_NATIVE_JOURNAL_ID_BYTES, MAX_RUNNER_NATIVE_PREPARATION_EVIDENCE_BYTES,
    MAX_RUNNER_TRANSPORT_REQUEST_BYTES, MAX_TERMINAL_EVIDENCE_BYTES,
    NativePreparationDispositionV1, NativePreparationPlatformExpectationV1,
    NativeSourceRejectionReasonV1, OperationalCurrentFinalVerificationAttemptV1,
    OperationalCurrentFinalVerificationParentV1, PersistedCommandDomainCleanup,
    PersistedCommandOutputCapture, PersistedCommandOutputSensitiveRejectionV1, PersistedCompletion,
    PersistedCompletionApplication, PersistedCompletionLiveStateAuthority,
    PersistedContainedCommandReleaseAdmission, PersistedCurrentFinalVerificationAttemptV1,
    PersistedCurrentFinalVerificationCaptureAcquisitionV1,
    PersistedCurrentFinalVerificationLaunchV1,
    PersistedCurrentFinalVerificationNativePreparationV1, PersistedEffect, PersistedFinishReceipt,
    PersistedMutationArtifact, PersistedOperationalCurrentFinalVerificationAttemptV1,
    PersistedPostCompletionRollback, PersistedRunnerEffectDispatchClaim,
    PersistedRunnerLaunchCleanupAdmission, PersistedRunnerLaunchPreparation, PersistedSprint,
    PersistedTerminalOutcome, PersistedTerminalProof,
    PostCompletionRollbackApplicationArtifactAuthority,
    PostCompletionRollbackApplicationArtifactAuthorityState, PostCompletionRollbackApplier,
    PostCompletionRollbackApplierRole, PostCompletionRollbackCleanup,
    PostCompletionRollbackCleanupEvidence, PostCompletionRollbackCleanupIntent,
    PostCompletionRollbackEndpointObservation, PostCompletionRollbackIntent,
    PostCompletionRollbackLaunchFailure, PostCompletionRollbackLaunchFailureKind,
    PostCompletionRollbackObservation, PostCompletionRollbackOutcome,
    PostCompletionRollbackOutcomeKind, PostCompletionRollbackPreconditionEvidence,
    PostCompletionRollbackStatus, PostCompletionRollbackTerminal,
    PostCompletionRollbackUnknownEvidence, PreV24CompletionLiveStateCaptureExemption,
    RunnerCleanupTerminalRecord, RunnerEffectObservationAuthority, RunnerEffectRequestAuthority,
    RunnerEffectTransportPermit, RunnerLaunchPreparationAttempt,
    RunnerLaunchPreparationDisposition, RunnerLaunchPreparationOutcome,
    SensitiveOutputCleanRunnerReferenceV1, SensitiveOutputCoreDumpSuppressionV1,
    SensitiveOutputDetectionPolicyReferenceV1, SensitiveOutputJournalHeadV1,
    SensitiveOutputRejectionRunnerReferenceV1, SensitiveOutputStagingNeutralizationReceiptV1,
    SprintApplicationAdmission, SprintApplicationDispatchAdmission, SprintApplicationPreparation,
    SprintFinalVerificationAdmission, SprintFinalVerificationDispatchAdmission,
    SprintLiveStateCaptureAdmission, SprintLiveStateCaptureDispatchAdmission, SprintTerminalProof,
    TaskAttemptCleanupDispositionPlan, TaskAttemptFormalCheckAdmission,
    TaskAttemptIntegrationAdmission, TaskDoneAssessment, TaskDoneClosedAttemptProof, TaskDoneProof,
    TaskDoneRequirement, TaskFormalCheckDispatchAdmission, TaskGraphProvenance,
    TaskIntegrationDispatchAdmission, current_command_output_capture_maximum_v1,
    current_final_verification_dispatch_claim_id,
    current_final_verification_v13_command_request_digest,
    post_completion_rollback_expected_endpoint_digest,
};
pub use live_state::{
    CompletionLiveStateApplicationLink, CompletionLiveStateCaptureAuthority,
    CompletionLiveStateCaptureLink, DESCRIPTOR_RELATIVE_WORKSPACE_MANIFEST_FORMAT_VERSION,
    DescriptorRelativeManifestEntry, DescriptorRelativeWorkspaceManifest, LiveStateCaptureBranch,
    LiveStateCaptureEvidence, LiveStateCaptureReceipt, LiveStateDriftBlockedProof,
    MAX_COMPLETION_LIVE_STATE_CAPTURE_LINK_BYTES, MAX_DESCRIPTOR_RELATIVE_MANIFEST_BYTES,
    MAX_DESCRIPTOR_RELATIVE_MANIFEST_ENTRIES, MAX_DESCRIPTOR_RELATIVE_MANIFEST_PATH_BYTES,
    MAX_LIVE_STATE_CAPTURE_EVIDENCE_BYTES, MAX_LIVE_STATE_CAPTURE_ID_BYTES,
    MAX_LIVE_STATE_CAPTURE_REQUEST_BYTES, MAX_LIVE_STATE_DRIFT_BLOCKED_PROOF_BYTES,
    MAX_LIVE_STATE_REQUIRED_CLEANUP_RECEIPTS, SprintLiveStateCapturePlan,
    SprintLiveStateCapturePlanCut, SprintLiveStateCaptureRequest,
};
pub use optimal_finish::{
    FinishCandidateAdmissibility, FinishCandidateCost, FinishCandidateGateStatus,
    FinishCandidateHardGate, OptimalFinishCandidate, OptimalFinishError,
    compare_optimal_finish_candidates, select_optimal_finish_candidate,
};
pub use scheduler::{
    CurrentV2SchedulerInput, SchedulePlan, SchedulerError, SchedulerInput,
    TaskAttemptSchedulerInput, path_scopes_conflict, plan_current_v2_worker_leases,
    plan_task_attempts, plan_worker_leases,
};
pub use state::{
    SprintState, StateTransitionError, TaskState, WorkerState, transition_current_v2_task,
};
pub use trust::{
    CompiledExecutionPolicy, ExecutionPolicyCompiler, ExecutionPolicyRequest, IssuedWorkspaceGrant,
    TrustRenewalReason, TrustRenewalRequest, WorkspaceGrantIssuer, WorkspaceGrantRequest,
    WorkspaceIdentity, assess_trust_renewal,
};

/// Current wire-contract version.
pub const CONTRACT_VERSION: u32 = 1;
